### Add Company
### 회사 ticker : MMM, NKE, QQQ, SPY, T, IBM, INTC, AAPL // 이거 자동화해야 된다.
POST localhost:8080/company
Content-Type: application/json

{
  "ticker": "INTC"
}

### Search Company
GET localhost:8080/company?ticker="O"

### Search All Company
GET localhost:8080/company

### Company Autocomplete
GET localhost:8080/company/autocomplete?keyword=I